# Generated by Django 4.1.5 on 2023-02-05 16:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0002_topic_room_host_mesage_room_topic"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mesage",
            new_name="Message",
        ),
    ]
